#!/usr/bin/bash

LINE=$(head -n 1 bitcoin.txt)
MIN_RATE=$(echo $LINE | jq '.rate')
MIN_TIME=$(echo $LINE | jq '.time')
MAX_RATE=$MIN_RATE
MAX_TIME=$MIN_TIME

while read PRICE
do
    RATE=$(echo $PRICE | jq '.rate')
    TIME=$(echo $PRICE | jq '.time')

    if [[ $MIN_RATE > $RATE  ]] ; then
        MIN_RATE=$RATE
        MIN_TIME=$TIME
    fi

    if [[ $MAX_RATE < $RATE  ]] ; then
        MAX_RATE=$RATE
        MAX_TIME=$TIME
    fi

done < bitcoin.txt

echo "The minimum rate so far is $MIN_RATE at $MIN_TIME"
echo "The maximum rate so far is $MAX_RATE at $MAX_TIME"

MAX_OBJECT=$(printf '{"Maximum": {"Rate":"%f","Time":"%s"}}' "$MAX_RATE" "$MAX_TIME")
MIN_OBJECT=$(printf '{"Minimum": {"Rate":"%f","Time":"%s"}}' "$MIN_RATE" "$MIN_TIME")

echo $MAX_OBJECT 
echo $MIN_OBJECT
